image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
