image: node:15.12-alpine3.13

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv ./build ./public
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master
